title: Diş Teli Fiyatları
description: >-
  <a href="https://www.periodent.net/dis-teli-fiyatlari/">Diş Teli Fiyatları</a>
  ortodonti ile ilgili tüm bilgiler noktasında sizi bekliyoruz.<a
  href="https://www.periodent.net/seffaf-dis-teli-fiyatlari/">şeffaf diş
  teli</a>
template:
  repo: dis-teli-fiyatlari-template
  name: dis-teli-fiyatlari
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Şeffaf Diş teli
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
      - type: createFile
    link: 'https://www.periodent.net/'
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
